services:
  - type: web
    name: ecosyntech-backend
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    repo: https://github.com/ecosyntech68vn/Ecosyntech-web