#!/bin/bash
# EcoSynTech - Auto Install Script V2.0
# 1-Click Installation with Auto .env Setup
# For Linux, macOS, Windows (Git Bash/WSL)

set -e

# ==========================================
# CONFIGURATION
# ==========================================
APP_NAME="EcoSynTech Local Core"
VERSION="3.0.0"
PORT=3000
DB_PATH="./data/ecosyntech.db"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# ==========================================
# FUNCTIONS
# ==========================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo ""
    echo "=========================================="
    echo -e "${CYAN}$1${NC}"
    echo "=========================================="
}

check_dependencies() {
    print_header "Checking Dependencies"
    
    # Check Node.js
    if ! command -v node &> /dev/null; then
        log_error "Node.js not found!"
        echo "Please install Node.js >= 18.0.0"
        echo "  curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -"
        echo "  sudo apt-get install -y nodejs"
        exit 1
    fi
    
    NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
    if [ "$NODE_VERSION" -lt 18 ]; then
        log_error "Node.js version must be >= 18.x (current: $(node -v))"
        exit 1
    fi
    
    log_success "Node.js: $(node -v)"
    
    # Check npm
    if ! command -v npm &> /dev/null; then
        log_error "npm not found!"
        exit 1
    fi
    
    log_success "npm: $(npm -v)"
    
    # Check git
    if ! command -v git &> /dev/null; then
        log_warn "Git not found - will use HTTPS download"
    else
        log_success "Git: $(git --version | cut -d' ' -f3)"
    fi
}

setup_env() {
    print_header "Setting Up Environment"
    
    # Create data directories
    log_info "Creating directories..."
    mkdir -p data data/backups logs models
    log_success "Directories created"
    
    # Create .env if not exists
    if [ ! -f .env ]; then
        log_info "Creating .env configuration..."
        
        cat > .env << EOF
# EcoSynTech Local Core V3.0 - Environment Configuration
# Generated by install.sh

# ==========================================
# SERVER CONFIG
# ==========================================
PORT=$PORT
NODE_ENV=development
HOST=0.0.0.0

# ==========================================
# DATABASE
# ==========================================
DB_PATH=$DB_PATH
DB_BACKUP_PATH=./data/backups

# ==========================================
# JWT SECURITY
# ==========================================
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "change-this-secret-key-change-this")
JWT_EXPIRY=86400

# ==========================================
# AI PROVIDERS (Optional - Free)
# ==========================================
AI_PROVIDER=deepseek
DEEPSEEK_API_KEY=
OLLAMA_URL=http://localhost:11434
OLLAMA_MODEL=llama3
OPENAI_API_KEY=
GEMINI_API_KEY=

# ==========================================
# EXTERNAL SERVICES (Optional)
# ==========================================
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
ZALO_APP_ID=
ZALO_APP_SECRET=
ZALO_WEBHOOK=

# ==========================================
# SECURITY
# ==========================================
CORS_ORIGIN=*
RATE_LIMIT_WINDOW=900000
RATE_LIMIT_MAX_REQUESTS=100

# ==========================================
# BACKUP
# ==========================================
AUTO_BACKUP_ENABLED=true
BACKUP_INTERVAL=daily
BACKUP_RETENTION=7

# ==========================================
# MONITORING
# ==========================================
LOG_LEVEL=info
METRICS_ENABLED=true
EOF
        
        log_success ".env created with auto-generated secrets"
    else
        log_info ".env already exists - skipping"
    fi
    
    # Set permissions
    chmod 600 .env
    log_success "Environment configured"
}

install_dependencies() {
    print_header "Installing Dependencies"
    
    log_info "Running npm install..."
    
    # Install with legacy peer deps for compatibility
    npm install --legacy-peer-deps 2>&1 | tail -5
    
    if [ $? -eq 0 ]; then
        log_success "Dependencies installed"
    else
        log_error "Failed to install dependencies"
        exit 1
    fi
}

test_system() {
    print_header "Testing System"
    
    log_info "Checking server.js..."
    if node --check server.js 2>/dev/null; then
        log_success "Server syntax OK"
    else
        log_error "Server syntax error"
        exit 1
    fi
    
    log_info "Running system audit..."
    if node src/intelligence/ai-skills/system-audit.skill.js 2>&1 | grep -q "AUDIT COMPLETED"; then
        log_success "System audit PASSED"
    else
        log_warn "System audit has warnings (may still work)"
    fi
}

start_server() {
    print_header "Starting Server"
    
    log_info "Starting $APP_NAME on port $PORT..."
    
    # Check if port is available
    if lsof -i :$PORT &> /dev/null; then
        log_warn "Port $PORT is in use. Checking..."
        
        # Try alternative port
        if [ "$PORT" = "3000" ]; then
            PORT=3001
            sed -i "s/^PORT=.*/PORT=$PORT/" .env 2>/dev/null || true
            log_info "Using alternative port: $PORT"
        else
            log_error "Port $PORT is busy"
            exit 1
        fi
    fi
    
    # Start in background
    npm start &
    SERVER_PID=$!
    
    # Wait for server to start
    sleep 3
    
    # Check if server is running
    if curl -s http://localhost:$PORT/health > /dev/null 2>&1; then
        print_header "INSTALLATION COMPLETE!"
        echo ""
        echo -e "${GREEN}Server is running at:${NC}"
        echo -e "  ${CYAN}http://localhost:$PORT${NC}"
        echo ""
        echo "Login credentials:"
        echo "  Username: admin"
        echo "  Password: admin123"
        echo ""
        echo -e "${YELLOW}IMPORTANT: Change password after first login!${NC}"
        echo ""
        echo "Next steps:"
        echo "  1. Open http://localhost:$PORT"
        echo "  2. Login with admin/admin123"
        echo "  3. Go to Settings > Change password"
        echo ""
    else
        log_error "Server failed to start. Check logs:"
        echo "  npm start"
    fi
}

setup_docker() {
    print_header "Docker Setup"
    
    read -p "Do you want to set up Docker? (y/N): " -n 1 -r
    echo
    
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        if ! command -v docker &> /dev/null; then
            log_error "Docker not installed"
            log_info "Install Docker: https://docs.docker.com/get-docker/"
            return 1
        fi
        
        log_info "Building Docker image..."
        docker-compose build
        
        log_info "Starting containers..."
        docker-compose up -d
        
        log_success "Docker is running"
        log_info "Access at http://localhost:$PORT"
    fi
}

show_help() {
    cat << EOF
Usage: $0 [OPTIONS]

Options:
    --help          Show this help message
    --docker       Set up Docker instead of running natively
    --lite         Install Lite version (512MB RAM)
    --skip-tests   Skip system tests
    --update       Update existing installation

Examples:
    $0              # Standard install
    $0 --docker     # Docker install
    $0 --lite       # Lite version (Raspberry Pi)
    $0 --update     # Update existing installation

EOF
}

# ==========================================
# MAIN
# ==========================================

# Parse arguments
SKIP_TESTS=0
DOCKER_SETUP=0
LITE_MODE=0
UPDATE_MODE=0

while [[ $# -gt 0 ]]; do
    case $1 in
        --help)
            show_help
            exit 0
            ;;
        --docker)
            DOCKER_SETUP=1
            shift
            ;;
        --lite)
            LITE_MODE=1
            shift
            ;;
        --skip-tests)
            SKIP_TESTS=1
            shift
            ;;
        --update)
            UPDATE_MODE=1
            shift
            ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Main execution
print_header "$APP_NAME V$VERSION - Auto Installer"

log_info "Starting installation..."

check_dependencies
install_dependencies
setup_env

if [ $SKIP_TESTS -eq 0 ]; then
    test_system
fi

if [ $DOCKER_SETUP -eq 1 ]; then
    setup_docker
else
    start_server
fi

log_success "Installation complete!"

# ==========================================
# END OF SCRIPT
# ==========================================